name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
      - 'Dev'
      - 'Test-*'
      - 'Feature-*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 5: Set branch name, tag, and repository name
      - name: Set branch name, tag, and repository name
        id: vars
        run: |
          # Convert username to lowercase
          USERNAME=$(echo "${GITHUB_ACTOR}" | tr '[:upper:]' '[:lower:]')

          # Extract repository name from owner/repo
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)

          # Extract branch name (strip 'refs/heads/')
          BRANCH_NAME=${GITHUB_REF##*/}

          # Replace slashes in branch name with dashes
          BRANCH_NAME=${BRANCH_NAME//\//-}

          # Get the current date and time in YYYY-MM-DD-HH.MM.SS format (with periods for time)
          TIMESTAMP=$(date +'%Y-%m-%d-%H.%M.%S')

          # Combine to form the image tag
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=${TIMESTAMP}-${BRANCH_NAME}" >> $GITHUB_ENV

      # Step 6: Build and push multi-platform Docker images
      - name: Build and push multi-platform Docker images
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ env.USERNAME }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }} \
            --tag ghcr.io/${{ env.USERNAME }}/${{ env.REPO_NAME }}:latest \
            --tag ghcr.io/${{ env.USERNAME }}/${{ env.REPO_NAME }}:${{ env.BRANCH_NAME }} \
            --push .

      # Step 7: Post-build cleanup (optional)
      - name: Remove dangling images
        run: |
          docker image prune -f

  deploy-pages:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # Step 3: Upload Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      
      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4